### PR TITLE
Check for alignment in debug mode

### PR DESCRIPTION
**Pull request by skgbanga**

### CODE REVIEW

**Comment by wjakob** [comment]
This looks good, but one request: can you remove the assertions in `dynamic.h`? Here, checking seems a bit overkill given that allocations will be done with the new over-aligned `new` operator.

**Comment by skgbanga** [comment]
@wjakob that's not always the case. Right now, my main use case involves

```cpp
static Derived map(void *ptr, size_t size)
```

I am converting some existing code to start using enoki, so those checks still do help. 

Upto you though. Personally I would prefer them, but can remove as well.

**Comment by wjakob** [comment]
Hi @skgbanga ,

the right place to put the assertion would be in `map()` then, instead of all of the other dynamic array-related operations.

Best,
Wenzel

**Comment by skgbanga** [comment]
@wjakob That makes sense to me.

Changes pushed.

**Comment by wjakob** [comment]
Merged, thanks!

**Pull request merged**
